// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GroupPolicy struct {
	ID        uuid.UUID   `json:"id"`
	GroupID   pgtype.UUID `json:"group_id"`
	PolicyID  uuid.UUID   `json:"policy_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PolicyID    uuid.UUID `json:"policy_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Profile struct {
	ID      uuid.UUID   `json:"id"`
	UserID  uuid.UUID   `json:"user_id"`
	Avatar  pgtype.Text `json:"avatar"`
	GroupID pgtype.UUID `json:"group_id"`
}

type Tenant struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Logo      pgtype.Text `json:"logo"`
	CreatedAt time.Time   `json:"created_at"`
}

type TenantGroup struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TenantPolicy struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	GroupID   pgtype.UUID `json:"group_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	TenantID          uuid.UUID `json:"tenant_id"`
	Password          string    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type UserGroup struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	GroupID   uuid.UUID   `json:"group_id"`
	CreatedAt time.Time   `json:"created_at"`
}
