// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: permission.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permission (name,description,policy_id) VALUES ($1,$2,$3) RETURNING id, name, description, policy_id, created_at
`

type CreatePermissionParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PolicyID    uuid.UUID `json:"policy_id"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Name, arg.Description, arg.PolicyID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PolicyID,
		&i.CreatedAt,
	)
	return i, err
}
