// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) (Tenant, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
