// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenantGroup(ctx context.Context, name string) (TenantGroup, error)
	CreateTenantPolicy(ctx context.Context, arg CreateTenantPolicyParams) (TenantPolicy, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UserGroup, error)
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantGroup(ctx context.Context, id uuid.UUID) (TenantGroup, error)
	GetTenantPolicy(ctx context.Context, id uuid.UUID) (TenantPolicy, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) (Tenant, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
